### ISSUE TITLE
Data is not transferred to Home Assistant

### ISSUE THREAD

**Issue by khaidakin** [Luligu/matterbridge-zigbee2mqtt#2]
I installed the latest version of Matterbridge and the matterbridge-zigbee2mqtt plugin. 
Added 2 devices to zigbee2mqtt (relay and temperature-humidity sensor). 
Scanned the codes and added Matterbridge to Home Assistant via Matter Server v5.4.1. 
Zigbee devices have been added to Home Assistant. 
I see data from zigbee devices in Matterbridge debug, but it is not transferred to Home Assistant.

**Comment by Luligu** [comment]
Published both matterbridge and matterbridge-zigbee2mqtt.
Can you try again ?

**Comment by khaidakin** [comment]
I installed new versions. Matterbridge sees the temperature sensor, but does not receive data from it
![2024-03-27_9-52-13](https://github.com/Luligu/matterbridge-zigbee2mqtt/assets/59665419/4b0a2161-e3d8-4d9c-ad48-cb5dba2790ba)

**Comment by khaidakin** [comment]
Here is the log from debug Matterbridge. But this data is not visible in Devices in the web interface

[09:59:22.422] [Zigbee2MQTT] Message for ***unknown*** entity: 0x00158d0003a27999 service: undefined payload: {
  battery: 97,
  humidity: 39.28,
  last_seen: '2024-03-27T09:59:22+02:00',
  linkquality: 165,
  power_outage_count: 15842,
  temperature: 23.1,
  voltage: 2995
}
[09:59:22.449] [Zigbee2MQTT] Message for ***unknown*** entity: 0x00158d0003a27999 service: undefined payload: {
  battery: 97,
  humidity: 39.28,
  last_seen: '2024-03-27T09:59:22+02:00',
  linkquality: 168,
  power_outage_count: 15842,
  temperature: 23.1,
  voltage: 2995
}
[09:59:27.688] [Zigbee2MQTT] Message for ***unknown*** entity: 0x00158d0003a27999 service: undefined payload: {
  battery: 97,
  humidity: 39.28,
  last_seen: '2024-03-27T09:59:27+02:00',
  linkquality: 201,
  power_outage_count: 15842,
  temperature: 23.28,
  voltage: 2995
}
[09:59:27.719] [Zigbee2MQTT] Message for ***unknown*** entity: 0x00158d0003a27999 service: undefined payload: {
  battery: 97,
  humidity: 52.19,
  last_seen: '2024-03-27T09:59:27+02:00',
  linkquality: 201,
  power_outage_count: 15842,
  temperature: 23.28,
  voltage: 2995
}
[09:59:37.949] [Zigbee2MQTT] Message for ***unknown*** entity: 0x00158d0003a27999 service: undefined payload: {
  battery: 97,
  humidity: 52.19,
  last_seen: '2024-03-27T09:59:37+02:00',
  linkquality: 204,
  power_outage_count: 15842,
  temperature: 23.34,
  voltage: 2995
}
[09:59:37.964] [Zigbee2MQTT] Message for ***unknown*** entity: 0x00158d0003a27999 service: undefined payload: {
  battery: 97,
  humidity: 43.7,
  last_seen: '2024-03-27T09:59:37+02:00',
  linkquality: 201,
  power_outage_count: 15842,
  temperature: 23.34,
  voltage: 2995
}

**Comment by Luligu** [comment]
The messages you see extraneus. They come from your mqtt broker. Probably old device no more in your zigbee2mqtt setup.

**Comment by khaidakin** [comment]
I removed the plugin and installed it again. Nothing has changed. In the console, debug mode I see incoming messages from zigbee2mqtt but there is no information from zigbee devices anywhere else

**Comment by khaidakin** [comment]
I reinstalled everything again on another server. Now I see this error: Error connecting to mqtt://localhost:1883: Connection refused: Unacceptable protocol version
What are the plugin requirements for the mqtt server?

**Comment by khaidakin** [comment]
I updated my version of mosquitto (2.0.11) and tried installing matterbridge-zigbee2mqtt again. While running matterbridge -add matterbridge-zigbee2mqtt I got the error:

 Connection established
[15:35:32.542] [Zigbee2MQTT] Started
[15:35:32.544] [Zigbee2MQTT] Subscribing topic: zigbee2mqtt-1/#
undefined:1
online
^

SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at Zigbee2MQTT.messageHandler (file:///usr/local/lib/nodejs/node-v18.19.1-linux-arm64/lib/node_modules/matterbridge-zigbee2mqtt/dist/zigbee2mqtt.js:312:31)
    at MqttClient.<anonymous> (file:///usr/local/lib/nodejs/node-v18.19.1-linux-arm64/lib/node_modules/matterbridge-zigbee2mqtt/dist/zigbee2mqtt.js:164:22)
    at MqttClient.emit (node:events:517:28)
    at handlePublish (/usr/local/lib/nodejs/node-v18.19.1-linux-arm64/lib/node_modules/matterbridge-zigbee2mqtt/node_modules/mqtt/build/lib/handlers/publish.js:97:20)
    at handle (/usr/local/lib/nodejs/node-v18.19.1-linux-arm64/lib/node_modules/matterbridge-zigbee2mqtt/node_modules/mqtt/build/lib/handlers/index.js:28:35)
    at work (/usr/local/lib/nodejs/node-v18.19.1-linux-arm64/lib/node_modules/matterbridge-zigbee2mqtt/node_modules/mqtt/build/lib/client.js:225:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

After this, Matterbridge stopped. 
When I try to start it again, it gets the same error again and stops
