### ISSUE TITLE
Climate control cooling / heating identification issue

### ISSUE THREAD

**Issue by robvanoostenrijk** [Luligu/matterbridge-zigbee2mqtt#89]
I have a Zigbee Climate control which only exposes `current_heating_setpoint` only:

[Tuya BAC-003](https://github.com/Koenkk/zigbee-herdsman-converters/blob/8c63663e6fed067c44208e59f4dbcc1166c11502/src/devices/tuya.ts#L3467)

The device can either heat or cool based on its mode.

In matterbridge-zigbee2mqtt I can see you are determining the cool or heat capability using the following logic:

```
const heat = zigbeeDevice.propertyMap.get('occupied_heating_setpoint') || zigbeeDevice.propertyMap.get('current_heating_setpoint');
const cool = zigbeeDevice.propertyMap.get('occupied_cooling_setpoint') || zigbeeDevice.propertyMap.get('current_cooling_setpoint');
```

But the zigbee2mqtt code restricts climate control devices to the following properties:

- occupied_heating_setpoint
- current_heating_setpoint
- occupied_cooling_setpoint
- unoccupied_heating_setpoint
- unoccupied_cooling_setpoint

Source: [src/lib/exposes.ts](https://github.com/Koenkk/zigbee-herdsman-converters/blob/8c63663e6fed067c44208e59f4dbcc1166c11502/src/lib/exposes.ts#L586)

I'm not clear on how to resolve this logic issue, but it looks like `current_cooling_setpoint` cannot be relied upon.
Upon testing Home Assistant only supports `current_heating_setpoint` for a single mode thermostat as well.

**Comment by Luligu** [comment]
Can you send me the link the zigbeesite of your thermo please?

**Comment by robvanoostenrijk** [comment]
Not sure what you are asking, but the device links are:
https://www.zigbee2mqtt.io/devices/BAC-003.html

Available via Chinese vendors here:
https://www.aliexpress.com/item/1005002593469162.html (The item provided is either the BAC-003 or BAC-002AZLB, but they are very similar and Zigbee behaves the same).

**Comment by robvanoostenrijk** [comment]
I've now switched to Matterbridge v1.7.0 with `-edge`.

My climate controls now do not show up through matterbridge-zigbee2mqtt, only through matterbridge-hass:

The log shows the following:

```
info [16:02:17.350] [Airconditioning - Den] MQTT message for device Airconditioning - Den payload: { current_heating_setpoint: 26, deadzone_temperature: 1, fan_mode: 'medium', linkquality: 51, local_temperature: 24.5, local_temperature_calibration: 0, preset: 'manual', schedule: null, state: 'OFF', system_mode: 'off', system_mode_device: 'cool' }
error [16:02:17.351] [Airconditioning - Den] getAttribute thermostat.occupiedHeatingSetpoint error: Endpoint Airconditioning-Den is in the inactive state
fatal [16:02:17.352] [Logger] Unhandled error detected: Airconditioning-Den endpoint number is not yet assigned; set number or await endpoint.construction to avoid this error at get number (file:///usr/local/l ... t/Endpoint.js:68:13) at ZigbeeDevice.updateAttributeIfChanged (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/entity.js:431:97) at file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/entity.js:146:34 at Array.forEach () at Zigbee2MQTT. (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/entity.js:119:37) at Zigbee2MQTT.emit (node:events:524:28) at Zigbee2MQTT.handleDeviceMessage (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/zigbee2mqtt.js:695:18) at Zigbee2MQTT.messageHandler (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/zigbee2mqtt.js:634:22) at MqttClient. (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/zigbee2mqtt.js:168:22) at MqttClient.emit (node:events:524:28)
fatal [16:02:17.352] [Matterbridge] Unhandled Exception detected at: Error: Airconditioning-Den endpoint number is not yet assigned; set number or await endpoint.construction to avoid this error at get number (file:///usr/local/l ... t/Endpoint.js:68:13) at ZigbeeDevice.updateAttributeIfChanged (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/entity.js:431:97) at file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/entity.js:146:34 at Array.forEach () at Zigbee2MQTT. (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/entity.js:119:37) at Zigbee2MQTT.emit (node:events:524:28) at Zigbee2MQTT.handleDeviceMessage (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/zigbee2mqtt.js:695:18) at Zigbee2MQTT.messageHandler (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/zigbee2mqtt.js:634:22) at MqttClient. (file:///usr/local/lib/node_modules/matterbridge-zigbee2mqtt/dist/zigbee2mqtt.js:168:22) at MqttClient.emit (node:events:524:28)
```

The Zigbee2MQTT does not expose `occupiedHeatingSetpoint` in its device definition, so unsure why Matterbridge is failing on this.

**Comment by Luligu** [comment]
Can you activate all debug (matterbridge and plugin) and send me a full log please?
If is not a problem for losing the configuration at controller would be perfect to put it on the whitelist so we have only this device in the log.
From the log you sent the device publish current_heating_setpoint but we need to understand what it exposes.

**Comment by robvanoostenrijk** [comment]
Requested files attached, including screenshot of the Google Home experience.

![Image](https://github.com/user-attachments/assets/fd6bd3aa-912a-4c39-a772-b49c5bf68ae5)

[matterbridge.log](https://github.com/user-attachments/files/18439127/matterbridge.log)

[bridge-devices.json](https://github.com/user-attachments/files/18439129/bridge-devices.json)

**Comment by Luligu** [comment]
Ok thanks now I get it.

These devices (you have 3 of them) keep the current_heating_setpoint even if they are in cool mode!
Furthermore system_mode_device: 'cool' is published but not exposed.

That is different from all the others I have seen and the moes one I used for testing here.

I will try something ...

Thanks.

**Comment by robvanoostenrijk** [comment]
The Z2M converter for it is maintained by me, I can make changes there as well if something does not seem right.

`system_mode_device` is actually a cheat to make the device support `on`/`off` in home assistant, which it normally doesn't support.

Default the device has a separate on/off and cool/heat/fan mode. The external converter extends system_mode to off/cool/heat/fan for home assistant. It uses system_mode_device to track what mode to set the device to once it's turned back on.

**Comment by robvanoostenrijk** [comment]
@Luligu, I have recently updated the Zigbee2MQTT herdsman converter for this device to be more logical.

If the device is operating in 2-pipe mode (cooling only) this can now be set as a device specific option.
This means the system_mode enum will be updated automatically to `["off", "cool", "fan_only"]` in the exposes definition.

Even though this is the case now, Matter still exposes a device with heating capability only (now `cool` and `fan_only` modes have actually disappeared). Note that in Home Assistant climate control all works as expected, `heat` is removed and `cool` & `fan_only` remain.

Updated log file and bridge-devices.json attached. 

[matterbridge.log](https://github.com/user-attachments/files/18601403/matterbridge.log)
[bridge-devices.json](https://github.com/user-attachments/files/18601404/bridge-devices.json)

**Comment by Luligu** [comment]
Hi,

I do apologize for being late with answer to your issue, but I'm publishing matterbridge 2.1.0 with all old api and imports removed... so is very complex and all must be done in the same moment.

Is due to be published on Sunday,

After I will go back to normal routine and you are at the top the list.

**Comment by robvanoostenrijk** [comment]
Resolved in matterbridge-zigbee2mqtt-2.4.5-dev.2
